version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: eafc-db-prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: eafc-server-prod
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNC=false
      - DB_TYPE=postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: eafc-client-prod
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data_prod:
